Event.create!([
  {name: "Team building", location: "Restaurant \"Slavinka\"", agenda: "This text is taken from the \"Lorem ipsum\" for testing the eProject4You.\r\nInteger in pharetra tellus. Nullam tincidunt enim nec dolor iaculis, at mattis turpis ullamcorper. Donec dictum ac lorem et lacinia. Proin nisl sem, vehicula vel justo id, ultricies iaculis neque. Sed a faucibus nulla. Sed tempus justo eu arcu ullamcorper, sit amet mollis odio posuere. Nullam blandit nunc sit amet tellus tempor feugiat. Cras ultrices, augue et hendrerit cursus, neque ipsum dignissim eros, in pulvinar odio odio non augue. Sed laoreet ligula ut sapien viverra rhoncus. Nullam dapibus, purus non aliquet sollicitudin, justo lorem facilisis arcu, eu varius nisl ex sollicitudin nulla. Praesent sit amet augue a arcu pellentesque iaculis. ", chairmen: "Zvonimir Kolumbic", term: "2017-12-21 07:57:00", annex_url: "teambuilding170727.pdf", appointment: "2017-01-29 09:00:00.000000", phase: "Hot"},
  {name: "Brainstorming", location: "Skype, group video chat", agenda: "This text is taken from the \"Lorem ipsum\" for testing the eProject4You.\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quam quam, mattis in turpis id, cursus posuere arcu. Proin in sapien vel nisi venenatis varius. Integer pharetra dictum tortor, in suscipit diam pellentesque aliquet. Nunc aliquet, nisi at accumsan tincidunt, ante felis porttitor ante, eu commodo est ex vestibulum ex. Phasellus a risus a nisl tristique tempor in eget risus. Maecenas imperdiet non odio non porttitor. Sed non arcu convallis, fermentum orci ut, maximus nisl. In augue metus, imperdiet id tellus quis, sodales vehicula mi.", chairmen: "Zvonimir Kolumbic", term: "2017-12-21 08:00:00", annex_url: "brainstorming.pdf", appointment: "2000-01-01 21:00:00.000000", phase: "Finished"}
])
Idea.create!([
  {name: "eBarter4You", summary: "##### VISION: \r\nBanking with time - the best currency.\r\n##### MISSION: \r\nExchange of wares and services with the calculation in the adjusted hours.\r\n##### USERS: \r\nPeople with excess/deficit of time/goods.\r\n##### EARNINGS: \r\n(a) project costs, \r\n(b) payments during X years the Y % of the project profit, \r\n(c) permanent payments the Z % of the project profit, \r\n(d) fee of the eBarter4You website members, \r\n(e) donations, \r\n(f) advertisements .", kind: "Combination", category: "Service", phase: "Definition", inventor: "Zvonimir Kolumbic", invented: "2017-12-19", necessary_budget: "12 000 €", annex_url: "ebarter4you.pdf"},
  {name: "eProject4You", summary: "##### VISION: \r\nHub for development of various projects from idea to market.\r\n##### MISSION: \r\nFinding: inventors, investors and experts. \r\nProjects: setup, startup and management.\r\n##### USERS: \r\nEntrepreneurs, inventors, investors, experts.\r\n##### EARNINGS: \r\n(a) project costs, \r\n(b) payments during X years the Y % of the project profit, \r\n(c) permanent payments the Z % of the project profit, \r\n(d) fee of the eProject4You website members, \r\n(e) donations, \r\n(f) advertisements.\r\n\r\n", kind: "Website", category: "Service", phase: "Development", inventor: "Zvonimir Kolumbic", invented: "2017-12-20", necessary_budget: "24 000 €", annex_url: "eproject4you.pdf"},
  {name: "BestSong", summary: "##### VISION: \r\nRepository of the top songs appropriate for different entertainments.\r\n##### MISSION: \r\nSelection and classification of songs by entertainment categories.\r\n##### USERS: \r\nEntertainment managers.\r\n##### EARNINGS: \r\n(a) fee of the TopSong website members, \r\n(b) donations, \r\n(c) advertisements.\r\n\r\n\r\n", kind: "Website", category: "Entertainment", phase: "Feasibility", inventor: "Zvonimir Kolumbic", invented: "2017-12-20", necessary_budget: "12 000 €", annex_url: "topsong.pdf"},
  {name: "Students4BF", summary: "Students for better future association", kind: "Combination", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""},
  {name: "Retiree4You", summary: "E Retired consulting experts association ", kind: "Website", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""},
  {name: "eRegionFormerYu", summary: "", kind: "Website", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""},
  {name: "CargoSpace4you", summary: "", kind: "Website", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""},
  {name: "MedicalTourisam4you", summary: "", kind: "Website", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""},
  {name: "HouseholdProblemSolver", summary: "", kind: "Website", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""},
  {name: "IdeaService4you", summary: "", kind: "Website", category: "Research", phase: "Demand", inventor: "", invented: "2018-04-10", necessary_budget: "", annex_url: ""}
])
Member.create!([
  {first_name: "Zvonimir", second_name: "Kolumbic", title: "prof., dr., dipl.ing.", image_url: "gravatar", kind: "Inventor", category: "Retired", nick_name: "Zvonko", email: "zvonimir.kolumbic1@ri.t-com.hr", skype_name: "zvonimir45", authorization_level: "admin", location: "Rijeka, Croatia", joined: "2017-12-21", summary: "Rodjen u Travniku 20.07.1945.\r\nZavrsio gimnaziju J. J. Zmaj u Novom Sadu.\r\nStrojarski inzenjer, diplomirao na Masinskom fakultetu u Novom Sadu.\r\nMagistar tehnickih znanosti, magistrirao na Fakultetu tehnickih nauka u Novom Sadu.\r\nDoktor tehnickih znanosti, doktorirao na Brodostrojarskom fakultetu u Zagrebu.", details_url: "zvonimirkolumbic.pdf", password_digest: "zv0n1m1r", visible: true},
  {first_name: "Marko", second_name: "Dundjer", title: "prof., dr., dipl.ing.", image_url: "https://tkojetko.irb.hr/files/pictures/IMG_12062.jpg", kind: "Expert", category: "Employed", nick_name: "Marko", email: "mdundjer@ffri.hr", skype_name: "mdundjer", authorization_level: "3", location: "Travnik, Bosna i Hercegovina", joined: "2017-12-21", summary: "Radi na odjelu Politehnika Sveučilišta u Rijeci.", details_url: "markodundjer.pdf", password_digest: "markodundjer", visible: false},
  {first_name: "Sinisa", second_name: "Kaludjersaki", title: "dipl.ing.", image_url: "https://pbs.twimg.com/profile_images/378800000631819723/8d140b916bf87e48311c02a814b51576_400x400.jpeg", kind: "Inventor", category: "Student", nick_name: "Sinisa", email: "sinisa.kaludjerski@novisad.rs", skype_name: "sinisakaludjerski", authorization_level: "3", location: "Novi Sad, Srbija", joined: "2017-12-21", summary: "U penziji.", details_url: "sinisakaludjerski.pdf", password_digest: "sinisakaludjerski", visible: true}
])
Project.create!([
  {name: "eProject4You", started_at: "2017-12-20", started_in: "Rijeka, Croatia", summary: "##### VISION: \r\nHub for development of various projects from idea to market.\r\n##### MISSION: \r\nFinding: inventors, investors and experts. \r\nProjects: setup, startup and management.\r\n##### USERS: \r\nEntrepreneurs, inventors, investors, experts.\r\n##### EARNINGS: \r\n(a) project costs, \r\n(b) payments during X years the Y % of the project profit, \r\n(c) permanent payments the Z % of the project profit, \r\n(d) fee of the eProject4You website members, \r\n(e) donations, \r\n(f) advertisements.", phase: "Preparation", kind: "Website", category: "Service", ceo: "Zvonimir Kolumbic", staff: 1, investor: "Zvonimir Kolumbic", budget: "0 €", deadline: "2017-12-20", annex_url: "eproject4you.pdf"},
  {name: "TopSong", started_at: "2017-12-20", started_in: "Rijeka, Croatia", summary: "##### VISION: \r\nRepository of the top songs appropriate for different entertainments.\r\n##### MISSION: \r\nSelection and classification of songs by entertainment categories.\r\n##### USERS: \r\nEntertainment managers.\r\n##### EARNINGS: \r\n(a) fee of the TopSong website members, \r\n(b) donations, \r\n(c) advertisements.\r\n", phase: "Preparation", kind: "Website", category: "Service", ceo: "Zvonimir Kolumbic", staff: 1, investor: "Zvonimir Kolumbic", budget: "0 €", deadline: "2017-12-20", annex_url: "topsong.pdf"},
  {name: "staka4you", started_at: "2017-12-20", started_in: "RIjeka, Croatia", summary: "##### VISION: \r\nComplete Cheat Sheet for website design aid.\r\n##### MISSION: \r\nDeveloping Cheat Sheet for: HTML, CSS, JavaScript, jQuery, Bootstrap, MySQL, PostgreSQL, Ruby, Ruby on Rails, Python, Django, php, Wordpress, BASH, C9, Design.\r\n##### USERS: \r\nMembers, website developers.\r\n##### EARNINGS: \r\n(a) fee of the DynamicCheatSheet website members, \r\n(b) donations, \r\n(c) advertisements.\r\n\r\n", phase: "Preparation", kind: "Website", category: "Service", ceo: "Zvonimir Kolumbic", staff: 1, investor: "Zvonimir Kolumbic", budget: "0 €", deadline: "2017-12-20", annex_url: "dynamiccheatsheet.pdf"},
  {name: "e-sale", started_at: "2018-04-10", started_in: nil, summary: "Rasprodja osobnih stvari", phase: "Preparation", kind: "Website", category: "Research", ceo: "Zvonimir Kolumbic", staff: nil, investor: "", budget: "", deadline: "2018-04-10", annex_url: ""},
  {name: "IdeaService4You", started_at: "2018-04-10", started_in: nil, summary: "", phase: "Preparation", kind: "Website", category: "Research", ceo: "", staff: nil, investor: "", budget: "", deadline: "2018-04-10", annex_url: ""}
])
Report.create!([
  {name: "Startup Business Ideas", author: "Martins Ferreira N. ", category: "News", level: "Engineering", summary: "## 30 Amazing Startup Business Ideas That’ll Make You Money\r\nWith so many startup business ideas, it can be hard to figure out which is worth pursuing.\r\nYou’ll want to create a store in a niche that’s not only profitable but also great for the long-term.\r\nYou may notice that a lot of the business ideas on this list have been growing in popularity recently.\r\nWhile jumping on a new trend can sometimes be risky – it can also be highly rewarding.\r\nSome of the ecommerce business ideas on this list have always been popular for a long time making it more competitive but less risky. However, all the niche examples on this list will help make you money.\r\nAlso, I helped put together this new video that outlines 10 new online business ideas – feel free to check this out as well:\r\n###1 Selfie Drones – Business Ideas\r\n###2 HIIT Equipment – Niche Examples\r\n###3 Smartwatches – Startup Ideas\r\n###4 Mirrorless Camera – Startup Business Ideas\r\n###5 ...", keywords: "business, ideas, startup", full_text_url: "https://www.oberlo.com/blog/business-ideas-that-make-money#1_Selfie_Drones_8211_Business_Ideas", published: "2018-01-22", author_detais_url: "vnmvnmhttps://www.oberlo.com/blog/author/nicole-martins-ferreira"},
  {name: "dznhzj", author: "Smale t.", category: "Comments", level: "Engineering", summary: "# 10 Organizations That Provide Support for Entrepreneurs\r\n1. Entrepreneurs' Organization, https://www.eonetwork.org/; \r\n2. FoundersCard, https://founderscard.com/; \r\n3. Young Entrepreneur Council, https://yec.co/; \r\n4. Young President's Organization, http://www.ypo.org/; \r\n5. Vistage, http://www.vistage.com/; \r\n6. Dynamite Circle, http://www.tropicalmba.com/dc/; \r\n7. The Entrepreneur's Club, http://www.tecglobal.org/; \r\n8. Ashoka, https://www.ashoka.org/en; \r\n9. The Association of Private, Enterprise Education; https://www.apee.org/; \r\n10. Startup Grind, https://www.startupgrind.com/.", keywords: "entrepreneuers, support", full_text_url: "https://www.entrepreneur.com/article/253283", published: "2015-12-02", author_detais_url: "https://www.entrepreneur.com/author/thomas-smale"},
  {name: "Billionaire Business Ideas", author: "Forbes Staff", category: "Experience", level: "Engineering", summary: "*Forbes Features America's Next Billionaire Business Ideas\r\nThe February 9 issue of Forbes magazine features billion-dollar business ideas from a list of 50 private American companies attracting attention for their sales growth and management talent (“Billion-Dollar Ideas,” p. 80).  The ten billion-dollar business ideas from Forbes’ 2015 list of America’s Most Promising Companies include:\r\n1. Seamless Collaboration: Helping businesses improve internal operations and boost productivity by making communication easier.  \r\n2. Customer Stalking: Enabling companies to track potential customers almost everywhere, even as they go from one device to another.\r\n3. ...\r\n", keywords: "business, idea", full_text_url: "http://www.forbes.com/sites/forbespr/2015/01/21/forbes-features-americas-next-billionaire-business-ideas/#e22f22a71f6d", published: "2015-01-21", author_detais_url: "https://www.forbes.com/sites/forbespr/#11a61d256c22"},
  {name: "ADM", author: "Quraishi S. A.", category: "Comments", level: "Engineering", summary: "## Low Cost or No Cost Startup Business Ideas\r\nRemember that no business in the world is easy to do, however, if you chose to run a business according to your aptitude, expertise and the skills set you have, chances of success are more.\r\n1 Arts & crafts business\r\n2 Interior designer\r\n3 Jewelry designer\r\n4 Webdesigning\r\n5 Web Development\r\n...", keywords: "business, idea", full_text_url: "https://www.startupguys.net/low-cost-or-no-cost-startup-business-ideas/", published: "2014-03-18", author_detais_url: "-"}
])
